ADMIN_ROLE = 1
REGULAR_ROLE = 2
CLOUDFRONT_HOST = 'http://dpaqzkfinvd5q.cloudfront.net'
S3_CREDENTIALS = { :access_key_id => ENV['AWS_ACCESS_KEY_ID'], :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'], :bucket => ENV['S3_BUCKET_NAME']}
BUCKET = ENV['S3_BUCKET_NAME'],
ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID'],
SECRET_ACCESS_KEY =  ENV['AWS_SECRET_ACCESS_KEY']
BHN_SALT = 49038409385
